# Generated by Django 6.0 on 2025-12-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('embadded', 'Embadded'), ('cyber', 'Cyber')], default='frontend', max_length=50),
        ),
    ]
