# Generated by Django 6.0 on 2025-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('embadded', 'Embadded'), ('cyber', 'Cyber'), ('other', 'Other')], default='frontend', max_length=50),
        ),
    ]
