# Generated by Django 5.2.8 on 2025-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
